Add unit role to data
CommunityDragon/CDTB pull request #105
Opened 2024-11-30 00:04 UTC by stelar7

Havent tested this yet, but should work in theory

2024-11-30 10:48 UTC, benoitryder requested changes

2024-11-30 10:48 UTC, benoitryder commented on cdtb/tftdata.py
> +
Unneeded change

2024-11-30 10:48 UTC, benoitryder commented on cdtb/tftdata.py
> +            roleKey = record.getv("CharacterRole", None)
```suggestion
            role_key = record.getv("CharacterRole", None)
```

2024-11-30 10:48 UTC, benoitryder commented on cdtb/tftdata.py
> +            role = "Unknown Role"
I see no reason for this fallback/default value. We should just use `None`.

2024-11-30 13:03 UTC, Morilli commented
I wonder if it could be worth exporting the whole `TFTCharacterRoleData` information as well...

2024-11-30 18:12 UTC, benoitryder commented
> I wonder if it could be worth exporting the whole `TFTCharacterRoleData` information as well...

We can start with just the name, then add roles data in a separate top-level entry.

2024-12-13 22:48 UTC, benoitryder commented
Replaced by #106

2024-12-13 22:48 UTC, closed without merging