New --patchline argument
CommunityDragon/CDTB pull request #66
Opened 2022-11-03 09:41 UTC by LeagueOfPoro

Added support for `--patchline pbe` argument as a working alternative to `--cdn`.

2022-11-03 18:49 UTC, benoitryder requested changes
Thanks for your PR! Several people had issues with that in the past so this will definiteily be helpful. :)

2022-11-03 18:49 UTC, benoitryder commented on cdragontoolbox/__main__.py
> +            conf['patchline'] = args.patchline
An error should be thrown if `--patchline` is set and storage type is not `patcher` (as for `--cdn`).
This is easy to do if `--patchline` defaults to `None` as suggested.

2022-11-05 11:31 UTC, benoitryder commented
Keeping `--patchline` is better IMHO, because it's more generic and matches directly the storage JSON format.

And you can use the following to have same default/fallback behavior:
```py
    storage_parser.add_argument('--patchline', choices=['live', 'pbe'], default=None,
                                help="use PBE patchline")
```
```py
        if args.patchline is not None:
            if conf['type'] == 'patcher':
                conf['patchline'] = args.patchline
            else:
                parser.error("--patchline is only supported for 'patcher' storage")
```

2022-11-08 18:46 UTC, LeagueOfPoro commented
I would argue --pbe makes for a more concise command. However, matching the JSON config makes sense. 
Changed

2022-11-08 20:54 UTC, merged